const API_BASE = location.hostname.endsWith('.github.io') ? 'https://123456654329.asro.jp' : 'https://123456654329.asro.jp';
const $ = id => document.getElementById(id);
const auth=$('auth'),authForm=$('authForm'),authSubmit=$('authSubmit'),authToggle=$('authToggle'),authError=$('authError');
const username=$('username'),password=$('password'),chatList=$('chatList'),chat=$('chat'),composer=$('composer'),input=$('input'),send=$('send'),provider=$('provider'),webSearch=$('webSearch'),useReferences=$('useReferences'),addReference=$('addReference'),logout=$('logout'),newChat=$('newChat'),status=$('status'),imageInput=$('imageInput'),attach=$('attach'),attachmentPreview=$('attachmentPreview');
let registerMode=false,currentChatId=null,controller=null,pendingImage=null,generationMode=false;
async function api(path,options={}){const res=await fetch(`${API_BASE}${path}`,{credentials:'include',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||`HTTP ${res.status}`);return data;}
function setLoggedIn(user){auth.classList.add('hidden');chat.classList.remove('hidden');composer.classList.remove('hidden');provider.value=user.provider||'auto';loadChats().catch(showError);}
function showError(e){renderMessage('assistant',`エラー: ${e.message}`);}
function ensureMessageActions(el,role){if(role!=='assistant')return;const actions=document.createElement('div');actions.className='message-actions';const copy=document.createElement('button');copy.type='button';copy.className='message-action';copy.textContent='コピー';copy.onclick=async()=>{try{await navigator.clipboard.writeText(el.dataset.raw||el.textContent||'');copy.textContent='コピー済み';setTimeout(()=>copy.textContent='コピー',1200);}catch{copy.textContent='コピーできません';setTimeout(()=>copy.textContent='コピー',1200);}};actions.appendChild(copy);el.appendChild(actions);}
function renderMessage(role,text){document.querySelector('.welcome')?.remove();const el=document.createElement('div');el.className=`message ${role}`;el.dataset.raw=text||'';el.textContent=text||'';chat.appendChild(el);ensureMessageActions(el,role);chat.scrollTop=chat.scrollHeight;return el;}
function renderImageMessage(url,prompt='生成画像'){const el=document.createElement('div');el.className='message assistant image-message';const img=document.createElement('img');img.src=url;img.alt=prompt;img.loading='lazy';el.appendChild(img);const actions=document.createElement('div');actions.className='image-actions';const regen=document.createElement('button');regen.type='button';regen.className='message-action';regen.textContent='もう一度生成';regen.onclick=async()=>{try{await generateImage(prompt);}catch(e){showError(e);}};const copy=document.createElement('button');copy.type='button';copy.className='message-action';copy.textContent='プロンプトをコピー';copy.onclick=async()=>{try{await navigator.clipboard.writeText(prompt);copy.textContent='コピー済み';setTimeout(()=>copy.textContent='プロンプトをコピー',1200);}catch{}};actions.append(regen,copy);el.appendChild(actions);chat.appendChild(el);chat.scrollTop=chat.scrollHeight;return el;}
function renderChatList(chats){chatList.innerHTML='';for(const item of chats){const row=document.createElement('div');row.className=`chat-row${item.id===currentChatId?' active':''}`;row.textContent=item.title;row.title=item.title;row.onclick=()=>openChat(item.id);chatList.appendChild(row);}}
async function loadChats(){const data=await api('/api/chats');renderChatList(data.chats);if(!data.chats.length)await createChat();else if(!currentChatId)await openChat(data.chats[0].id);}
async function refreshChats(){renderChatList((await api('/api/chats')).chats);}
async function createChat(){if(controller)controller.abort();const data=await api('/api/chats',{method:'POST',body:'{}'});currentChatId=data.chat.id;chat.innerHTML='<div class="welcome"><h1>こんにちは！</h1><p>somenAIに何でも聞いてみてね。</p></div>';await refreshChats();input.focus();}
async function openChat(id){if(controller)controller.abort();const data=await api(`/api/chats/${id}`);currentChatId=id;chat.innerHTML='';if(!data.messages.length)chat.innerHTML='<div class="welcome"><h1>こんにちは！</h1><p>somenAIに何でも聞いてみてね。</p></div>';else data.messages.forEach(m=>renderMessage(m.role,m.content));await refreshChats();input.focus();}
function resizeImage(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const max=1600,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.max(2,Math.round(img.width*scale));canvas.height=Math.max(2,Math.round(img.height*scale));canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);resolve({mimeType:'image/webp',base64:canvas.toDataURL('image/webp',.82)});};img.onerror=reject;img.src=reader.result;};reader.onerror=reject;reader.readAsDataURL(file);});}
imageInput.onchange=async()=>{const file=imageInput.files?.[0];if(!file)return;try{pendingImage=await resizeImage(file);attachmentPreview.classList.remove('hidden');attachmentPreview.textContent=`📎 ${file.name}（画像を添付中）`;}catch{alert('画像を読み込めませんでした。');pendingImage=null;}imageInput.value='';};
attach.onclick=()=>imageInput.click();
async function generateImage(text){send.disabled=true;attach.disabled=true;send.textContent='生成中…';status.textContent='Cloudflare FLUX.2 klein 4Bで画像を生成中…';const data=await api(`/api/chats/${currentChatId}/generate-image`,{method:'POST',body:JSON.stringify({prompt:text})});renderMessage('user',`🎨 ${text}`);const image=data.image;const url=`${API_BASE}/api/chats/${currentChatId}/generated/${encodeURIComponent(image.id)}/${encodeURIComponent(image.filename)}`;renderImageMessage(url,text);}
async function streamMessage(text){controller=new AbortController();send.disabled=true;attach.disabled=true;send.textContent='生成中…';status.textContent=webSearch.checked?'Web検索中…':useReferences.checked?'参考資料を確認中…':'生成中…';const body={message:text,webSearch:webSearch.checked,useReferences:useReferences.checked};if(pendingImage)body.image=pendingImage;const res=await fetch(`${API_BASE}/api/chats/${currentChatId}/messages/stream`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json',Accept:'text/event-stream'},body:JSON.stringify(body),signal:controller.signal});if(!res.ok){const d=await res.json().catch(()=>({}));throw new Error(d.error||`HTTP ${res.status}`);}const reader=res.body.getReader(),decoder=new TextDecoder();let buffer='',assistant=null,providerMeta=null;while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const events=buffer.split('\n\n');buffer=events.pop()||'';for(const event of events){const line=event.split('\n').find(v=>v.startsWith('data: '));if(!line)continue;const d=JSON.parse(line.slice(6));if(d.notice)status.textContent=d.notice;if(d.searchProvider)status.textContent=`${d.searchProvider==='exa'?'Exa':'Tavily'}で検索しました`;if(d.text){if(!assistant){assistant=renderMessage('assistant','');providerMeta=document.createElement('div');providerMeta.className='message-meta provider';assistant.appendChild(providerMeta);}assistant.dataset.raw=(assistant.dataset.raw||'')+d.text;const raw=assistant.dataset.raw;const meta=assistant.querySelector('.message-meta.provider');const actions=assistant.querySelector('.message-actions');assistant.textContent=raw;if(meta)assistant.appendChild(meta);if(actions)assistant.appendChild(actions);else ensureMessageActions(assistant,'assistant');if(d.provider)meta.textContent=`使用モデル: ${d.provider==='groq'?'Groq / Qwen':'Gemini'}`;chat.scrollTop=chat.scrollHeight;}}}}
async function addReferenceMaterial(){const title=prompt('参考資料のタイトルを入力');if(!title?.trim())return;const content=prompt('参考資料の本文を入力');if(!content?.trim())return;try{await api('/api/references',{method:'POST',body:JSON.stringify({title,content})});alert('参考資料を追加しました。');useReferences.checked=true;}catch(e){alert(e.message);}}
function setAuthMode(register){registerMode=register;authSubmit.textContent=register?'アカウントを作成':'ログイン';authToggle.textContent=register?'ログインはこちら':'新規登録はこちら';password.autocomplete=register?'new-password':'current-password';authError.textContent='';}
authToggle.onclick=()=>setAuthMode(!registerMode);authForm.onsubmit=async e=>{e.preventDefault();authSubmit.disabled=true;authError.textContent='';try{const p=registerMode?'/api/auth/register':'/api/auth/login';setLoggedIn((await api(p,{method:'POST',body:JSON.stringify({username:username.value,password:password.value})})).user);}catch(e){authError.textContent=e.message;}finally{authSubmit.disabled=false;}};
provider.onchange=async()=>{try{await api('/api/settings/ai',{method:'PATCH',body:JSON.stringify({provider:provider.value})});}catch(e){alert(e.message);}};addReference.onclick=addReferenceMaterial;newChat.onclick=()=>createChat().catch(showError);logout.onclick=async()=>{await api('/api/auth/logout',{method:'POST',body:'{}'}).catch(()=>{});location.reload();};
composer.onsubmit=async e=>{e.preventDefault();if(controller)return;const text=input.value.trim();if(generationMode){if(!text)return;input.value='';try{await generateImage(text);await refreshChats();}catch(e){showError(e);}finally{generationMode=false;controller=null;send.disabled=false;attach.disabled=false;send.textContent='送信';input.placeholder='メッセージを入力…';status.textContent='';input.focus();}return;}if(!text&&!pendingImage)return;input.value='';if(text)renderMessage('user',text);else renderMessage('user','📎 画像を送信');try{await streamMessage(text);await refreshChats();}catch(e){if(e.name!=='AbortError')showError(e);}finally{controller=null;pendingImage=null;attachmentPreview.classList.add('hidden');attachmentPreview.textContent='';status.textContent='';send.disabled=false;attach.disabled=false;send.textContent='送信';input.focus();}};
input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();composer.requestSubmit();}};
const modeButton=document.createElement('button');modeButton.type='button';modeButton.className='mode-button';modeButton.textContent='🎨';modeButton.title='画像生成モード';modeButton.onclick=()=>{generationMode=!generationMode;input.placeholder=generationMode?'生成したい画像を説明してね…':'メッセージを入力…';modeButton.textContent=generationMode?'💬':'🎨';};composer.insertBefore(modeButton,composer.firstChild);
(async()=>{try{setLoggedIn((await api('/api/auth/me')).user);}catch{setAuthMode(false);}})();
