const API_BASE='https://123456654329.asro.jp';
const $=id=>document.getElementById(id);
const auth=$('auth'),authForm=$('authForm'),authSubmit=$('authSubmit'),authToggle=$('authToggle'),authError=$('authError');
const username=$('username'),password=$('password'),chatList=$('chatList'),chat=$('chat'),composer=$('composer'),input=$('input'),send=$('send');
const provider=$('provider'),webSearch=$('webSearch'),useReferences=$('useReferences'),addReference=$('addReference'),logout=$('logout'),newChat=$('newChat'),status=$('status');
const imageInput=$('imageInput'),cameraInput=$('cameraInput'),attach=$('attach'),attachmentPreview=$('attachmentPreview'),modeButton=$('modeButton');
const sidebar=$('sidebar'),backdrop=$('backdrop'),menuButton=$('menuButton');
let registerMode=false,currentChatId=null,controller=null,generationMode=false,pendingImages=[];

async function api(path,options={}){const res=await fetch(API_BASE+path,{credentials:'include',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||`HTTP ${res.status}`);return data}
function toast(text,error=false){document.querySelector('.toast')?.remove();const el=document.createElement('div');el.className=`toast${error?' error':''}`;el.textContent=text;Object.assign(el.style,{position:'fixed',left:'50%',bottom:'24px',transform:'translateX(-50%)',zIndex:'3000',padding:'10px 15px',borderRadius:'10px',background:error?'#c0392b':'#202123',color:'#fff',fontSize:'13px',boxShadow:'0 8px 30px #0003'});document.body.appendChild(el);setTimeout(()=>el.remove(),2200)}
function closeMenu(){sidebar.classList.remove('open');backdrop.classList.remove('open')}
menuButton.onclick=()=>{sidebar.classList.toggle('open');backdrop.classList.toggle('open')};backdrop.onclick=closeMenu;
function showError(e){toast(e.message||String(e),true)}
function clearChat(){chat.innerHTML='<div class="welcome"><h1>こんにちは！</h1><p>somenAIに何でも聞いてみてね。</p></div>'}
function addActions(el){if(el.querySelector('.message-actions'))return;const actions=document.createElement('div');actions.className='message-actions';const copy=document.createElement('button');copy.type='button';copy.className='message-action';copy.textContent='コピー';copy.onclick=async()=>{try{await navigator.clipboard.writeText(el.dataset.raw||'');copy.textContent='コピー済み';setTimeout(()=>copy.textContent='コピー',1200)}catch{toast('コピーできませんでした',true)}};actions.appendChild(copy);el.appendChild(actions)}
function renderMessage(role,text){document.querySelector('.welcome')?.remove();const el=document.createElement('div');el.className=`message ${role}`;el.dataset.raw=text||'';el.textContent=text||'';chat.appendChild(el);if(role==='assistant')addActions(el);chat.scrollTop=chat.scrollHeight;return el}
function renderUserImages(text,files){document.querySelector('.welcome')?.remove();const el=document.createElement('div');el.className='message user user-image-message';el.dataset.raw=text||'';if(text){const p=document.createElement('div');p.className='image-message-text';p.textContent=text;el.appendChild(p)}const grid=document.createElement('div');grid.className='user-image-grid';files.forEach((file,i)=>{const img=document.createElement('img');img.src=URL.createObjectURL(file);img.alt=`送信画像 ${i+1}`;img.onload=()=>URL.revokeObjectURL(img.src);grid.appendChild(img)});el.appendChild(grid);chat.appendChild(el);chat.scrollTop=chat.scrollHeight}
function renderGeneratedImage(url,prompt){document.querySelector('.welcome')?.remove();const el=document.createElement('div');el.className='message assistant image-message';const img=document.createElement('img');img.src=url;img.alt=prompt||'生成画像';img.loading='lazy';el.appendChild(img);const actions=document.createElement('div');actions.className='image-actions';const regen=document.createElement('button');regen.type='button';regen.className='message-action';regen.textContent='もう一度生成';regen.onclick=()=>generateImage(prompt);const copy=document.createElement('button');copy.type='button';copy.className='message-action';copy.textContent='プロンプトをコピー';copy.onclick=async()=>{try{await navigator.clipboard.writeText(prompt||'');copy.textContent='コピー済み';setTimeout(()=>copy.textContent='プロンプトをコピー',1200)}catch{}};actions.append(regen,copy);el.appendChild(actions);chat.appendChild(el);chat.scrollTop=chat.scrollHeight}
function renderChatList(chats){chatList.innerHTML='';for(const item of chats){const row=document.createElement('div');row.className=`chat-row${item.id===currentChatId?' active':''}`;const title=document.createElement('span');title.className='chat-title';title.textContent=item.title||'新しいチャット';const more=document.createElement('button');more.type='button';more.className='chat-more';more.textContent='•••';more.setAttribute('aria-label','チャット操作');more.onclick=e=>{e.stopPropagation();openChatMenu(more,item)};row.append(title,more);row.onclick=()=>openChat(item.id);chatList.appendChild(row)}}
async function refreshChats(){renderChatList((await api('/api/chats')).chats||[])}
async function loadChats(){const data=await api('/api/chats');renderChatList(data.chats||[]);if(!data.chats?.length)await createChat();else if(!currentChatId)await openChat(data.chats[0].id)}
async function createChat(){if(controller)controller.abort();closeMenu();const data=await api('/api/chats',{method:'POST',body:'{}'});currentChatId=data.chat.id;clearChat();await refreshChats();input.focus()}
async function openChat(id){if(controller)controller.abort();closeMenu();const data=await api(`/api/chats/${id}`);currentChatId=id;chat.innerHTML='';if(!data.messages?.length)clearChat();else data.messages.forEach(m=>renderMessage(m.role,m.content));await refreshChats();input.focus()}
function openChatMenu(anchor,item){document.querySelector('.popover')?.remove();const menu=document.createElement('div');menu.className='popover';const rename=document.createElement('button');rename.textContent='✏️ 名前を変更';const del=document.createElement('button');del.className='danger';del.textContent='🗑️ チャットを削除';menu.append(rename,del);document.body.appendChild(menu);const r=anchor.getBoundingClientRect();menu.style.left=`${Math.max(8,Math.min(innerWidth-190,r.right-190))}px`;menu.style.top=`${Math.min(innerHeight-100,r.bottom+6)}px`;rename.onclick=()=>{menu.remove();renameChat(item.id,item.title||'')};del.onclick=()=>{menu.remove();deleteChat(item.id,item.title||'')};setTimeout(()=>{const outside=e=>{if(!menu.contains(e.target)&&e.target!==anchor){menu.remove();document.removeEventListener('click',outside)}};document.addEventListener('click',outside)},0)}
function modal(title,subtitle=''){document.querySelector('.modal-backdrop')?.remove();const b=document.createElement('div');b.className='modal-backdrop';const m=document.createElement('section');m.className='modal';const close=document.createElement('button');close.className='modal-close';close.type='button';close.textContent='×';const h=document.createElement('div');h.className='modal-title';h.textContent=title;const s=document.createElement('div');s.className='modal-subtitle';s.textContent=subtitle;const body=document.createElement('div');body.className='modal-body';m.append(close,h,s,body);b.appendChild(m);document.body.appendChild(b);const done=()=>b.remove();close.onclick=done;b.onclick=e=>{if(e.target===b)done()};return{body,close:done}}
async function renameChat(id,current){const m=modal('チャット名を変更','分かりやすい名前に変更できます');const i=document.createElement('input');i.value=current;i.maxLength=80;i.placeholder='チャット名';const a=document.createElement('div');a.className='modal-actions';const c=document.createElement('button');c.className='btn btn-secondary';c.textContent='キャンセル';const s=document.createElement('button');s.className='btn btn-primary';s.textContent='保存';a.append(c,s);m.body.append(i,a);c.onclick=m.close;s.onclick=async()=>{const title=i.value.trim();if(!title)return toast('チャット名を入力してね',true);s.disabled=true;try{await api(`/api/chats/${id}`,{method:'PATCH',body:JSON.stringify({title})});m.close();await refreshChats();toast('チャット名を変更しました')}catch(e){s.disabled=false;showError(e)}};i.focus();i.select()}
async function deleteChat(id,title){const m=modal('チャットを削除','この操作は元に戻せません。');const p=document.createElement('p');p.textContent=`「${title}」を削除しますか？`;const a=document.createElement('div');a.className='modal-actions';const c=document.createElement('button');c.className='btn btn-secondary';c.textContent='キャンセル';const d=document.createElement('button');d.className='btn btn-primary';d.style.background='#c0392b';d.textContent='削除';a.append(c,d);m.body.append(p,a);c.onclick=m.close;d.onclick=async()=>{d.disabled=true;try{await api(`/api/chats/${id}`,{method:'DELETE'});m.close();if(currentChatId===id)currentChatId=null;const list=(await api('/api/chats')).chats||[];if(list.length)await openChat(list[0].id);else await createChat();toast('チャットを削除しました')}catch(e){d.disabled=false;showError(e)}}}
function setAuthMode(register){registerMode=register;authSubmit.textContent=register?'アカウントを作成':'ログイン';authToggle.textContent=register?'ログインはこちら':'新規登録はこちら';password.autocomplete=register?'new-password':'current-password';authError.textContent=''}
function setLoggedIn(user){auth.classList.add('hidden');chat.classList.remove('hidden');composer.classList.remove('hidden');provider.value=user?.provider||'auto';loadChats().catch(showError)}
authToggle.onclick=()=>setAuthMode(!registerMode);authForm.onsubmit=async e=>{e.preventDefault();authSubmit.disabled=true;authError.textContent='';try{const path=registerMode?'/api/auth/register':'/api/auth/login';setLoggedIn((await api(path,{method:'POST',body:JSON.stringify({username:username.value.trim(),password:password.value})})).user)}catch(e){authError.textContent=e.message}finally{authSubmit.disabled=false}};
provider.onchange=async()=>{try{await api('/api/settings/ai',{method:'PATCH',body:JSON.stringify({provider:provider.value})});toast('AI設定を保存しました')}catch(e){showError(e)}};
addReference.onclick=()=>{const m=modal('参考資料を追加','登録した資料をRAGで回答の参考にできます。');const title=document.createElement('input');title.placeholder='タイトル';const content=document.createElement('textarea');content.rows=9;content.placeholder='参考資料の本文';const a=document.createElement('div');a.className='modal-actions';const c=document.createElement('button');c.className='btn btn-secondary';c.textContent='キャンセル';const s=document.createElement('button');s.className='btn btn-primary';s.textContent='資料を追加';a.append(c,s);m.body.append(title,content,a);c.onclick=m.close;s.onclick=async()=>{if(!title.value.trim()||!content.value.trim())return toast('タイトルと本文を入力してね',true);s.disabled=true;try{await api('/api/references',{method:'POST',body:JSON.stringify({title:title.value.trim(),content:content.value.trim()})});useReferences.checked=true;m.close();toast('参考資料を追加しました')}catch(e){s.disabled=false;showError(e)}};title.focus()};
logout.onclick=async()=>{await api('/api/auth/logout',{method:'POST',body:'{}'}).catch(()=>{});location.reload()};newChat.onclick=()=>createChat().catch(showError);
function openSettings(){const m=modal('設定','somenAIの動作をまとめて変更できます。');const ai=document.createElement('div');ai.className='setting-block';const h=document.createElement('h3');h.textContent='AIモデル';const p=document.createElement('p');p.className='setting-description';p.textContent='使用するAIを選択します。';const sel=document.createElement('select');[['auto','自動'],['gemini','Gemini'],['groq','Groq / Qwen']].forEach(([v,t])=>{const o=document.createElement('option');o.value=v;o.textContent=t;sel.appendChild(o)});sel.value=provider.value;sel.onchange=()=>{provider.value=sel.value;provider.dispatchEvent(new Event('change'))};ai.append(h,p,sel);const features=document.createElement('div');features.className='setting-block';const fh=document.createElement('h3');fh.textContent='便利機能';features.appendChild(fh);[['webSearch','Web検索','最新のWeb情報を回答に取り込む'],['useReferences','参考資料RAG','登録した資料を回答の参考にする']].forEach(([id,label,desc])=>{const row=document.createElement('label');row.className='modal-toggle';const span=document.createElement('span');span.textContent=label;const small=document.createElement('small');small.textContent=desc;small.style.display='block';small.style.color='#777';small.style.fontWeight='400';span.appendChild(small);const cb=document.createElement('input');cb.type='checkbox';cb.checked=$(id).checked;cb.onchange=()=>$(id).checked=cb.checked;row.append(span,cb);features.appendChild(row)});const a=document.createElement('div');a.className='modal-actions';const done=document.createElement('button');done.className='btn btn-primary';done.textContent='閉じる';done.onclick=m.close;a.appendChild(done);m.body.append(ai,features,a)}
const settingsButton=document.createElement('button');settingsButton.className='btn btn-secondary full';settingsButton.type='button';settingsButton.textContent='⚙️ 設定';settingsButton.onclick=openSettings;document.querySelector('.sidebar-bottom').insertBefore(settingsButton,addReference);

function fileToData(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
function loadImage(file){return new Promise((resolve,reject)=>{const u=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(u);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(u);reject(new Error('画像を読み込めませんでした'))};img.src=u})}
async function resizeImage(file){const img=await loadImage(file);const max=1600,scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight));if(scale===1)return{mimeType:file.type||'image/jpeg',base64:await fileToData(file)};const c=document.createElement('canvas');c.width=Math.max(2,Math.round(img.naturalWidth*scale));c.height=Math.max(2,Math.round(img.naturalHeight*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);return{mimeType:'image/webp',base64:c.toDataURL('image/webp',.82)}}
async function compositeImages(files){const imgs=await Promise.all(files.map(loadImage));const width=Math.min(1600,Math.max(...imgs.map(i=>i.naturalWidth)));const heights=imgs.map(i=>Math.max(1,Math.round(i.naturalHeight*(width/i.naturalWidth))));const c=document.createElement('canvas');c.width=width;c.height=heights.reduce((a,b)=>a+b,0);const ctx=c.getContext('2d');let y=0;imgs.forEach((img,i)=>{ctx.drawImage(img,0,y,width,heights[i]);y+=heights[i]});return{mimeType:'image/webp',base64:c.toDataURL('image/webp',.82)}}
function renderAttachmentPreview(){attachmentPreview.innerHTML='';if(!pendingImages.length){attachmentPreview.classList.add('hidden');return}attachmentPreview.classList.remove('hidden');const head=document.createElement('div');head.className='attachment-head';head.innerHTML=`<strong>添付画像</strong><span>${pendingImages.length} / 2</span>`;attachmentPreview.appendChild(head);const grid=document.createElement('div');grid.className='attachment-grid';pendingImages.forEach((file,i)=>{const tile=document.createElement('div');tile.className='attachment-tile';const img=document.createElement('img');img.src=URL.createObjectURL(file);img.alt=`画像 ${i+1}`;img.onload=()=>URL.revokeObjectURL(img.src);const num=document.createElement('span');num.className='attachment-index';num.textContent=i+1;const x=document.createElement('button');x.type='button';x.className='attachment-remove';x.textContent='×';x.onclick=()=>{pendingImages.splice(i,1);renderAttachmentPreview()};tile.append(img,num,x);grid.appendChild(tile)});attachmentPreview.appendChild(grid);if(pendingImages.length<2){const add=document.createElement('button');add.type='button';add.className='attachment-add';add.textContent='＋ 画像を追加';add.onclick=openImagePicker;attachmentPreview.appendChild(add)}}
function addImages(files){for(const file of files){if(!file.type?.startsWith('image/'))continue;if(pendingImages.length>=2){toast('画像は2枚まで送れます',true);break}pendingImages.push(file)}renderAttachmentPreview()}
function openImagePicker(){document.querySelector('.picker-backdrop')?.remove();const b=document.createElement('div');b.className='picker-backdrop';const p=document.createElement('section');p.className='picker';const h=document.createElement('h2');h.textContent='画像を選択';const sub=document.createElement('p');sub.textContent='最大2枚まで添付できます。';const photo=document.createElement('button');photo.textContent='▧  写真・ファイルから選択';const camera=document.createElement('button');camera.textContent='⌾  カメラで撮影';const cancel=document.createElement('button');cancel.className='cancel';cancel.textContent='キャンセル';p.append(h,sub,photo,camera,cancel);b.appendChild(p);document.body.appendChild(b);const close=()=>b.remove();b.onclick=e=>{if(e.target===b)close()};cancel.onclick=close;photo.onclick=()=>{close();imageInput.click()};camera.onclick=()=>{close();cameraInput.click()}}
imageInput.onchange=e=>{addImages([...(e.target.files||[])]);e.target.value=''};cameraInput.onchange=e=>{addImages([...(e.target.files||[])]);e.target.value=''};attach.onclick=openImagePicker;
document.addEventListener('paste',e=>{const files=[...(e.clipboardData?.files||[])].filter(f=>f.type?.startsWith('image/'));if(files.length){e.preventDefault();addImages(files)}});composer.addEventListener('dragover',e=>{if([...e.dataTransfer?.types||[]].includes('Files')){e.preventDefault();composer.classList.add('dragging')}});composer.addEventListener('dragleave',()=>composer.classList.remove('dragging'));composer.addEventListener('drop',e=>{const files=[...(e.dataTransfer?.files||[])].filter(f=>f.type?.startsWith('image/'));if(files.length){e.preventDefault();addImages(files)}composer.classList.remove('dragging')});
async function prepareImage(){if(!pendingImages.length)return null;return pendingImages.length===1?resizeImage(pendingImages[0]):compositeImages(pendingImages)}
async function generateImage(prompt){if(!prompt?.trim()||!currentChatId)return;send.disabled=true;modeButton.disabled=true;attach.disabled=true;send.textContent='生成中…';status.textContent='画像を生成中…';renderMessage('user',`🎨 ${prompt.trim()}`);try{const data=await api(`/api/chats/${currentChatId}/generate-image`,{method:'POST',body:JSON.stringify({prompt:prompt.trim()})});const image=data.image;const url=`${API_BASE}/api/chats/${currentChatId}/generated/${encodeURIComponent(image.id)}/${encodeURIComponent(image.filename)}`;renderGeneratedImage(url,prompt.trim());await refreshChats()}finally{send.disabled=false;modeButton.disabled=false;attach.disabled=false;send.textContent='送信';status.textContent=''}}
async function streamMessage(text){controller=new AbortController();send.disabled=true;modeButton.disabled=true;attach.disabled=true;send.textContent='生成中…';status.textContent=webSearch.checked?'Web検索中…':useReferences.checked?'参考資料を確認中…':'生成中…';const body={message:text,webSearch:webSearch.checked,useReferences:useReferences.checked};if(pendingImages.length)body.image=await prepareImage();const res=await fetch(`${API_BASE}/api/chats/${currentChatId}/messages/stream`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json',Accept:'text/event-stream'},body:JSON.stringify(body),signal:controller.signal});if(!res.ok){const d=await res.json().catch(()=>({}));throw new Error(d.error||`HTTP ${res.status}`)}const reader=res.body.getReader(),decoder=new TextDecoder();let buffer='',assistant=null,raw='',providerName='';while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const chunks=buffer.split('\n\n');buffer=chunks.pop()||'';for(const chunk of chunks){const line=chunk.split('\n').find(x=>x.startsWith('data: '));if(!line)continue;let d;try{d=JSON.parse(line.slice(6))}catch{continue}if(d.notice)status.textContent=d.notice;if(d.searchProvider)status.textContent=`${d.searchProvider==='exa'?'Exa':'Tavily'}で検索しました`;if(d.provider)providerName=d.provider;if(d.text){if(!assistant)assistant=renderMessage('assistant','');raw+=d.text;assistant.textContent=raw;assistant.dataset.raw=raw;addActions(assistant);if(providerName){const meta=document.createElement('div');meta.className='message-meta provider-meta';meta.textContent=`使用モデル: ${providerName==='groq'?'Groq / Qwen':'Gemini'}`;assistant.appendChild(meta)}chat.scrollTop=chat.scrollHeight}}}}
composer.onsubmit=async e=>{e.preventDefault();if(controller)return;const text=input.value.trim();if(generationMode){if(!text)return;input.value='';generationMode=false;modeButton.classList.remove('mode-active');modeButton.textContent='🎨';input.placeholder='メッセージを入力…';try{await generateImage(text)}catch(err){showError(err)}return}if(!text&&!pendingImages.length)return;const files=[...pendingImages];if(files.length)renderUserImages(text,files);else renderMessage('user',text);input.value='';pendingImages=[];renderAttachmentPreview();try{await streamMessage(text);await refreshChats()}catch(err){if(err.name!=='AbortError')showError(err)}finally{controller=null;send.disabled=false;modeButton.disabled=false;attach.disabled=false;send.textContent='送信';status.textContent=''}};
input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();composer.requestSubmit()}};
modeButton.onclick=()=>{generationMode=!generationMode;modeButton.classList.toggle('mode-active',generationMode);modeButton.textContent=generationMode?'💬':'🎨';input.placeholder=generationMode?'生成したい画像を説明してね…':'メッセージを入力…';input.focus()};
(async()=>{try{setLoggedIn((await api('/api/auth/me')).user)}catch{setAuthMode(false)}})();
