(() => {
  const $ = id => document.getElementById(id);
  const input = $('imageInput'), attach = $('attach'), preview = $('attachmentPreview'), composer = $('composer');
  if (!input || !attach || !preview || !composer) return;
  const originalChange = input.onchange;
  let files = [];
  const toast = text => { document.querySelector('.ui-toast')?.remove(); const t=document.createElement('div'); t.className='ui-toast'; t.textContent=text; document.body.appendChild(t); setTimeout(()=>t.remove(),1800); };
  const setInputFile = file => { const dt=new DataTransfer(); dt.items.add(file); input.files=dt.files; };
  const resetOriginal = () => { try { const dummy=new File(['x'],'reset.txt',{type:'text/plain'}); setInputFile(dummy); originalChange?.call(input,{target:input}); } catch {} setTimeout(()=>{input.value='';},80); };
  const load = file => new Promise((resolve,reject)=>{const u=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(u);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(u);reject(new Error('image'))};img.src=u});
  const composite = async () => { const imgs=await Promise.all(files.map(load)); const width=Math.min(1600,Math.max(...imgs.map(i=>i.naturalWidth))); const heights=imgs.map(i=>Math.max(1,Math.round(i.naturalHeight*(width/i.naturalWidth)))); const canvas=document.createElement('canvas'); canvas.width=width; canvas.height=heights.reduce((a,b)=>a+b,0); const ctx=canvas.getContext('2d'); let y=0; imgs.forEach((img,i)=>{ctx.drawImage(img,0,y,width,heights[i]);y+=heights[i]}); return new Promise(resolve=>canvas.toBlob(blob=>resolve(new File([blob],'somenai-images.webp',{type:'image/webp'})),'image/webp',.84)); };
  const syncComposite = async () => { try { const file=files.length===1?files[0]:await composite(); setInputFile(file); if(originalChange) await originalChange.call(input,{target:input}); renderPreview(); } catch { toast('画像を読み込めませんでした'); } };
  const renderPreview = () => { if(!files.length){preview.classList.add('hidden');preview.innerHTML='';return;} preview.classList.remove('hidden'); preview.innerHTML=`<div class="attachment-head"><strong>添付画像</strong><span>${files.length} / 2</span></div>`; const grid=document.createElement('div');grid.className='attachment-grid'; files.forEach((file,i)=>{const tile=document.createElement('div');tile.className='attachment-tile';const img=document.createElement('img');img.src=URL.createObjectURL(file);img.alt=`画像 ${i+1}`;img.onload=()=>URL.revokeObjectURL(img.src);const num=document.createElement('span');num.className='attachment-index';num.textContent=String(i+1);const x=document.createElement('button');x.type='button';x.className='attachment-remove';x.textContent='×';x.setAttribute('aria-label',`画像${i+1}を削除`);x.onclick=()=>{files.splice(i,1);renderPreview();if(files.length)syncComposite();else resetOriginal()};tile.append(img,num,x);grid.appendChild(tile)});preview.appendChild(grid);if(files.length<2){const add=document.createElement('button');add.type='button';add.className='attachment-add';add.innerHTML='＋ 画像を追加';add.onclick=openPicker;preview.appendChild(add)}};
  const addFile = file => {if(!file?.type?.startsWith('image/'))return;if(files.length>=2){toast('画像は2枚まで送れます');return}files.push(file);renderPreview();syncComposite()};
  function openPicker(){document.querySelector('.image-picker-backdrop')?.remove();const back=document.createElement('div');back.className='image-picker-backdrop';back.innerHTML=`<section class="image-picker" role="dialog" aria-modal="true"><div class="image-picker-grabber"></div><div class="image-picker-title"><strong>画像を選択・追加</strong><button type="button" class="image-picker-close">×</button></div><div class="image-picker-sub">${files.length?`あと${2-files.length}枚追加できます`:'最大2枚まで選択できます'}</div><button type="button" class="image-pick-option" data-pick="photos"><span class="pick-icon">▧</span><span><b>写真ライブラリ</b><small>端末の写真から選択</small></span></button><button type="button" class="image-pick-option" data-pick="camera"><span class="pick-icon">⌾</span><span><b>カメラで撮影</b><small>撮影した写真を追加</small></span></button><button type="button" class="image-pick-option" data-pick="file"><span class="pick-icon">□</span><span><b>ファイルから選択</b><small>ファイルアプリから追加</small></span></button><button type="button" class="image-pick-option" data-pick="paste"><span class="pick-icon">▣</span><span><b>コピーした画像を貼り付け</b><small>画像をコピーしてチャット欄で貼り付け</small></span></button><button type="button" class="image-picker-cancel">キャンセル</button></section>`;document.body.appendChild(back);const close=()=>back.remove();back.querySelector('.image-picker-close').onclick=close;back.querySelector('.image-picker-cancel').onclick=close;back.onclick=e=>{if(e.target===back)close()};back.querySelectorAll('[data-pick]').forEach(btn=>btn.onclick=()=>{const p=btn.dataset.pick;close();if(p==='camera')$('cameraInput')?.click();else if(p==='paste')toast('画像をコピーして、チャット欄で貼り付けてね');else input.click()})}
  input.onchange=e=>{const chosen=[...(e.target.files||[])].filter(f=>f.type.startsWith('image/'));if(!chosen.length)return;chosen.slice(0,2-files.length).forEach(addFile);input.value=''};
  $('cameraInput')?.addEventListener('change',e=>{[...(e.target.files||[])].forEach(addFile);e.target.value=''});
  attach.onclick=openPicker;
  document.addEventListener('paste',e=>{const pasted=[...(e.clipboardData?.files||[])].filter(f=>f.type.startsWith('image/'));if(pasted.length)pasted.slice(0,2-files.length).forEach(addFile)});
  composer.addEventListener('dragover',e=>{if(e.dataTransfer?.types?.includes('Files')){e.preventDefault();composer.classList.add('dragging')}});
  composer.addEventListener('dragleave',()=>composer.classList.remove('dragging'));
  composer.addEventListener('drop',e=>{composer.classList.remove('dragging');const dropped=[...(e.dataTransfer?.files||[])].filter(f=>f.type.startsWith('image/'));if(dropped.length){e.preventDefault();dropped.slice(0,2-files.length).forEach(addFile)}});
  window.__somenAIImages={
    get files(){return [...files]},
    async getPayload(){if(files.length) await syncComposite(); return true},
    clearVisual(){files=[];input.value='';renderPreview()},
    clear(){files=[];resetOriginal();renderPreview()}
  };
})();